before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 4
  - npm run buid &
  - npm run server &
  - sleep 4
  - firefox http://localhost:5777/utest/ &
  - sleep 4
 
script:
  - "npm test"
 
language: node_js
node_js:
  - "6.6.0"
